language: cpp

compiler:
  - gcc
  - clang

before_install:
  - git submodule update --init --recursive

install: 
  - cmake . -DJSONCPP_WITH_TESTS=OFF -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF

script:
 - $CXX --version 
 - make

os:
  - linux
  - osx